'use strict';
const fullName = 'Aaditya Desai';
console.log('value of fullName:', fullName);
const isCool = true;
console.log('value of isCool:', isCool);
const totalPets = 0;
console.log('value of totalPets:', totalPets);
console.log('typeof fullName:', typeof 'fullName');
console.log('typeof isCool:', typeof true);
console.log('typeof totalPets:', typeof 0);
const empty = null;
console.log('empty:', empty);
console.log('typeof empty:', typeof null);
const nothing = undefined;
console.log('nothing:', nothing);
console.log('typeof nothing:', typeof undefined);
