'use strict';
const colors = ['red', 'white', 'blue'];
console.log('value of colors[0]:', colors[0]);
console.log('value of colors[1]:', colors[1]);
console.log('value of colors[2]:', colors[2]);
const america = `${colors[0]}, ${colors[1]}, ${colors[2]}`;
console.log('America is', america);
colors[2] = 'green';
const mexico = `${colors[0]}, ${colors[1]}, ${colors[2]}`;
console.log('Mexico is', mexico);
console.log('value of colors:', colors);
console.log('typeof colors:', typeof colors);
const students = ['Frank', 'Bob', 'Chris', 'David'];
const numberOfStudents = students.length;
console.log(`There are ${numberOfStudents} students in the class`);
const lastIndex = numberOfStudents - 1;
const lastStudent = students[lastIndex];
console.log(`The last student in the array is ${lastStudent}`);
console.log('value of students:', students);
console.log('typeof students:', typeof students);
